"""Add RenewalDesk owner email

Revision ID: 385d6260b08a
Revises: 52d603c1e0ee
Create Date: 2026-08-21 14:53:56.457043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '385d6260b08a'
down_revision: Union[str, Sequence[str], None] = '52d603c1e0ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('renewaldesk_renewal_items', sa.Column('owner_email', sa.String(length=320), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('renewaldesk_renewal_items', 'owner_email')
    # ### end Alembic commands ###
