"""Add RenewalDesk reminder deliveries

Revision ID: 52d603c1e0ee
Revises: ef1a7f12b09e
Create Date: 2026-08-21 13:57:31.943740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d603c1e0ee'
down_revision: Union[str, Sequence[str], None] = 'ef1a7f12b09e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('renewaldesk_reminder_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('renewal_item_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['renewal_item_id'], ['renewaldesk_renewal_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('renewal_item_id', 'channel', 'scheduled_for', name='uq_renewaldesk_reminder_delivery_occurrence')
    )
    op.create_index(op.f('ix_renewaldesk_reminder_deliveries_renewal_item_id'), 'renewaldesk_reminder_deliveries', ['renewal_item_id'], unique=False)
    op.create_index(op.f('ix_renewaldesk_reminder_deliveries_tenant_id'), 'renewaldesk_reminder_deliveries', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_renewaldesk_reminder_deliveries_tenant_id'), table_name='renewaldesk_reminder_deliveries')
    op.drop_index(op.f('ix_renewaldesk_reminder_deliveries_renewal_item_id'), table_name='renewaldesk_reminder_deliveries')
    op.drop_table('renewaldesk_reminder_deliveries')
    # ### end Alembic commands ###
