"""add AssetTrack developer API keys

Revision ID: 4b94903229c6
Revises: 68979228986a
Create Date: 2026-09-05 22:06:41.931341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b94903229c6'
down_revision: Union[str, Sequence[str], None] = '68979228986a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assettrack_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assettrack_api_keys_created_at'), 'assettrack_api_keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_assettrack_api_keys_created_by_user_id'), 'assettrack_api_keys', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_assettrack_api_keys_key_prefix'), 'assettrack_api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_assettrack_api_keys_revoked_at'), 'assettrack_api_keys', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_assettrack_api_keys_tenant_id'), 'assettrack_api_keys', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_assettrack_api_keys_token_hash'), 'assettrack_api_keys', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assettrack_api_keys_token_hash'), table_name='assettrack_api_keys')
    op.drop_index(op.f('ix_assettrack_api_keys_tenant_id'), table_name='assettrack_api_keys')
    op.drop_index(op.f('ix_assettrack_api_keys_revoked_at'), table_name='assettrack_api_keys')
    op.drop_index(op.f('ix_assettrack_api_keys_key_prefix'), table_name='assettrack_api_keys')
    op.drop_index(op.f('ix_assettrack_api_keys_created_by_user_id'), table_name='assettrack_api_keys')
    op.drop_index(op.f('ix_assettrack_api_keys_created_at'), table_name='assettrack_api_keys')
    op.drop_table('assettrack_api_keys')
    # ### end Alembic commands ###
