"""add AssetTrack service history

Revision ID: 68979228986a
Revises: b65879127d71
Create Date: 2026-09-05 21:58:06.824385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68979228986a'
down_revision: Union[str, Sequence[str], None] = 'b65879127d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assettrack_service_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('details', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assettrack_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assettrack_service_events_asset_id'), 'assettrack_service_events', ['asset_id'], unique=False)
    op.create_index(op.f('ix_assettrack_service_events_event_type'), 'assettrack_service_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_assettrack_service_events_occurred_at'), 'assettrack_service_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_assettrack_service_events_tenant_id'), 'assettrack_service_events', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assettrack_service_events_tenant_id'), table_name='assettrack_service_events')
    op.drop_index(op.f('ix_assettrack_service_events_occurred_at'), table_name='assettrack_service_events')
    op.drop_index(op.f('ix_assettrack_service_events_event_type'), table_name='assettrack_service_events')
    op.drop_index(op.f('ix_assettrack_service_events_asset_id'), table_name='assettrack_service_events')
    op.drop_table('assettrack_service_events')
    # ### end Alembic commands ###
