"""Create AssetTrack assets

Revision ID: 6d93e32da36a
Revises: e7b3a1d9c2f4
Create Date: 2026-08-20 17:23:18.759057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d93e32da36a'
down_revision: Union[str, Sequence[str], None] = 'e7b3a1d9c2f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assettrack_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assettrack_assets_tenant_id'), 'assettrack_assets', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assettrack_assets_tenant_id'), table_name='assettrack_assets')
    op.drop_table('assettrack_assets')
    # ### end Alembic commands ###
