"""expand AssetTrack asset registry

Revision ID: b65879127d71
Revises: b9c3e5f7d124
Create Date: 2026-09-05 21:40:51.231661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b65879127d71'
down_revision: Union[str, Sequence[str], None] = 'b9c3e5f7d124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assettrack_assets', sa.Column('external_id', sa.String(length=100), nullable=True))
    op.add_column('assettrack_assets', sa.Column('asset_type', sa.String(length=50), server_default='other', nullable=False))
    op.add_column('assettrack_assets', sa.Column('manufacturer', sa.String(length=200), nullable=True))
    op.add_column('assettrack_assets', sa.Column('model', sa.String(length=200), nullable=True))
    op.add_column('assettrack_assets', sa.Column('serial_number', sa.String(length=200), nullable=True))
    op.add_column('assettrack_assets', sa.Column('status', sa.String(length=50), server_default='active', nullable=False))
    op.add_column('assettrack_assets', sa.Column('attributes', sa.JSON(), server_default='{}', nullable=False))
    op.add_column('assettrack_assets', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.alter_column('assettrack_assets', 'updated_at',
               existing_type=sa.DateTime(), server_default=None)
    op.create_index(op.f('ix_assettrack_assets_asset_type'), 'assettrack_assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_assettrack_assets_serial_number'), 'assettrack_assets', ['serial_number'], unique=False)
    op.create_index(op.f('ix_assettrack_assets_status'), 'assettrack_assets', ['status'], unique=False)
    op.create_unique_constraint('uq_assettrack_assets_tenant_external_id', 'assettrack_assets', ['tenant_id', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_assettrack_assets_tenant_external_id', 'assettrack_assets', type_='unique')
    op.drop_index(op.f('ix_assettrack_assets_status'), table_name='assettrack_assets')
    op.drop_index(op.f('ix_assettrack_assets_serial_number'), table_name='assettrack_assets')
    op.drop_index(op.f('ix_assettrack_assets_asset_type'), table_name='assettrack_assets')
    op.drop_column('assettrack_assets', 'updated_at')
    op.drop_column('assettrack_assets', 'attributes')
    op.drop_column('assettrack_assets', 'status')
    op.drop_column('assettrack_assets', 'serial_number')
    op.drop_column('assettrack_assets', 'model')
    op.drop_column('assettrack_assets', 'manufacturer')
    op.drop_column('assettrack_assets', 'asset_type')
    op.drop_column('assettrack_assets', 'external_id')
    # ### end Alembic commands ###
