"""Add tenant ownership to customers

Revision ID: 1a242a5c4ecc
Revises: 40ea7d9167fd
Create Date: 2026-08-16 22:34:53.026729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a242a5c4ecc'
down_revision: Union[str, Sequence[str], None] = '40ea7d9167fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customers",
        sa.Column("tenant_id", sa.Integer(), nullable=True),
    )
    op.create_index(
        op.f("ix_customers_tenant_id"),
        "customers",
        ["tenant_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_customers_tenant_id_tenants",
        "customers",
        "tenants",
        ["tenant_id"],
        ["id"],
    )

    op.execute(
        sa.text(
            """
            INSERT INTO tenants (name, slug, created_at)
            VALUES (
                'JobFlow Legacy Workspace',
                'jobflow-legacy',
                CURRENT_TIMESTAMP
            )
            ON CONFLICT (slug) DO NOTHING
            """
        )
    )

    op.execute(
        sa.text(
            """
            UPDATE customers
            SET tenant_id = (
                SELECT id
                FROM tenants
                WHERE slug = 'jobflow-legacy'
            )
            WHERE tenant_id IS NULL
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_customers_tenant_id_tenants",
        "customers",
        type_="foreignkey",
    )
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_column('customers', 'tenant_id')
    # ### end Alembic commands ###
