"""Add commercialization tenant lifecycle

Revision ID: 58cf3d616a02
Revises: b1bbbebad53f
Create Date: 2026-08-19 22:09:10.286419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58cf3d616a02'
down_revision: Union[str, Sequence[str], None] = 'b1bbbebad53f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('converted_tenant_id', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('converted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_leads_converted_tenant_id'), 'leads', ['converted_tenant_id'], unique=True)
    op.create_foreign_key(
        'fk_leads_converted_tenant_id_tenants',
        'leads',
        'tenants',
        ['converted_tenant_id'],
        ['id'],
    )
    op.add_column(
        'tenants',
        sa.Column(
            'status',
            sa.String(length=50),
            nullable=False,
            server_default='active',
        ),
    )
    op.alter_column(
        'tenants',
        'status',
        server_default=None,
    )
    op.add_column(
        'tenants',
        sa.Column(
            'suspended_at',
            sa.DateTime(),
            nullable=True,
        ),
    )
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_column('tenants', 'suspended_at')
    op.drop_column('tenants', 'status')
    op.drop_constraint(
        'fk_leads_converted_tenant_id_tenants',
        'leads',
        type_='foreignkey',
    )
    op.drop_index(op.f('ix_leads_converted_tenant_id'), table_name='leads')
    op.drop_column('leads', 'converted_at')
    op.drop_column('leads', 'converted_tenant_id')
    # ### end Alembic commands ###
